# Generated by Django 4.1.7 on 2023-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('folder', models.FileField(upload_to='%Y/folders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
