# Generated by Django 4.1.7 on 2023-03-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followersaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersAccount',
            new_name='FollowersCount',
        ),
    ]
