# Generated by Django 4.1.4 on 2023-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='accounts.Account')),
                ('task_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
