# Generated by Django 4.1.6 on 2023-02-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on-hold', 'On-hold'), ('done', 'Done')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='account.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lists', to='project.project_list')),
            ],
        ),
    ]
